/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "Linux skunk-HP-ProBook-450-G2 3.19.0-25-generic x86_64"
#define LGL_COMPILED "dimanche 11 février 2018, 18:52:46 (UTC+0100)"
#define LGL_RELEASED "Sat Oct 13 14:05:26 CEST 2012"
#define LGL_VERSION "ala"
#define LGL_ID "b02aa1a04343558c4252b5f4a723be021964f652"
